language: csharp
mono: none

notifications:
  email: false

branches:
  only:
    - master

matrix:
  include:
    - os: linux 
      dist: trusty # Ubuntu 14.04
      dotnet: 2.1
    - os: osx
      dotnet: 2.1.300
      osx_image: xcode8.3 # dotnet requires at least this version

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then ulimit -S -n 4096; fi

script:
  - dotnet build ./Sender/Sender.csproj -c Release -f netcoreapp2.1
  - dotnet build ./Reciver/Reciver.csproj -c Release -f netcoreapp2.1
